[env]
TERM = "alacritty"

[font]
size = 16.0
normal.family = "Hack Nerd Font"

[keyboard]
bindings = [
  { key = "F", mods = "Command|Control", action = "ToggleSimpleFullscreen" },
  { key = "Minus", mods = "Alt|Shift", chars = "\u001b[95;3u" },
  { key = "Equals", mods = "Alt|Shift", chars = "\u001b[43;3u" },
  { key = "Space", mods = "Command|Shift", action = "ToggleViMode" },
]

[mouse]
hide_when_typing = true

[window]
decorations = "Transparent"
dynamic_padding = true
option_as_alt = "OnlyLeft"
title = "Alacritty"
padding = { x = 5, y = 22 }
dimensions = { columns = 120, lines = 40 }
blur = true
opacity = 0.95

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

# [terminal.shell]
# program = "/bin/zsh"
# args = ["-l", "-c", "tmux attach || tmux"]
# args = ["-l", "-c", "zellij attach --index 0 --create"]
