"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, for = "macos" },
  { run = 'code "$@"', block = true, for = "macos" },
]
