git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --tabs=2 -s
  commit:
    signOff: true
gui:
  theme:
    activeBorderColor:
      - '#7e9cd8' # Muted blue
      - bold
    inactiveBorderColor:
      - '#a3b8ef' # Pastel gray-blue
    optionsTextColor:
      - '#c8c093' # Soft white
    selectedLineBgColor:
      - '#2d4f67' # Deep muted blue
    cherryPickedCommitBgColor:
      - '#3c4f5a' # Calm muted gray
    cherryPickedCommitFgColor:
      - '#7fb4ca' # Pastel blue
    unstagedChangesColor:
      - '#e82424' # Muted red
    defaultFgColor:
      - '#dcd7ba' # Soft white
    searchingActiveBorderColor:
      - '#7e9cd8' # Muted blue
  authorColors:
    '*': '#a3b8ef' # Pastel gray-blue
