[default.extend-words]
nin = "nin"
calender = "calendar"
resuit = "result"
mutatation = "mutation"
recod = "record"
recoder = "recorder"
als = "als"
prouduct = 'product'
noice = "noice"
answre = "answer"
prve = "prev"
prolbem = "problem"
